image:
  repository: cloudzero/cloudwatch-agent
  tag: cz-cloudwatchagent-0853e59.1
  pullPolicy: IfNotPresent

clusterName: cluster_name

resources:
  limits:
    cpu: 100m
    memory: 300Mi
  requests:
    cpu: 50m
    memory: 50Mi

serviceAccount:
  create: true
  name:

hostNetwork: true

nodeSelector: {}

tolerations: []

affinity: {}

annotations: {}

agentConfig: |
  {
    "logs": {
      "metrics_collected": {
        "kubernetes": {
          "cluster_name": "{{ .Values.clusterName }}",
          "metrics_collection_interval": 60
        }
      },
      "force_flush_interval": 5
    }
  }
