apiVersion: v2
name: cloudzero-prometheus-agent
description: A wrapper chart around Prometheus for running in agent mode.
type: application
version: 0.0.1
appVersion: "v2.50.1"
dependencies:
  - name: prometheus
    version: "25.17.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
