apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudzero-cloudwatch-metrics.fullname" . }}
  labels:
    {{- include "cloudzero-cloudwatch-metrics.labels" . | nindent 4 }}
data:
  cwagentconfig.json: |
{{ .Values.agentConfig | indent 4 }}
