apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "cloudzero-cloudwatch-metrics.fullname" . }}
  labels:
    {{- include "cloudzero-cloudwatch-metrics.labels" . | nindent 4 }}
{{- with .Values.daemonsetLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      {{- include "cloudzero-cloudwatch-metrics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudzero-cloudwatch-metrics.labels" . | nindent 8 }}
{{- with .Values.podLabels }}
{{ toYaml . | indent 8 }}
{{- end }}
      {{- if .Values.annotations }}
      annotations:
        {{- toYaml .Values.annotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "cloudzero-cloudwatch-metrics.serviceAccountName" . }}
      hostNetwork: {{ .Values.hostNetwork }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # Please don't change below envs
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CI_VERSION
          value: "k8s/1.3.0"
        - name: TRACK_REPLICA_SETS
          value: {{ printf "%v" .Values.trackReplicaSets | default true | quote }}
        - name: DOCKER_HOST
          value: 127.0.0.1:2375
        - name: CONTAINERD_ADDRESS
          value: 127.0.0.1:2375
        # Please don't change the mountPath
        volumeMounts:
        - name: cwagentconfig
          mountPath: /etc/cwagentconfig
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
        - name: dockersock
          mountPath: /var/run/docker.sock
          readOnly: true
        - name: varlibdocker
          mountPath: /var/lib/docker
          readOnly: true
        - name: containerdsock
          mountPath: {{ .Values.containerdSockPath | default "/run/containerd/containerd.sock" }}
          readOnly: true
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: devdisk
          mountPath: /dev/disk
          readOnly: true
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      - name: proxy-container
        image: ghcr.io/cloudzero/docker-socket-proxy:cz_base
        imagePullPolicy: Always
        ports:
        - containerPort: 2375
        - containerPort: 2376
        resources: { }
        volumeMounts:
        - name: haproxypid
          mountPath: /run/haproxy.pid
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
        - name: dockersock
          mountPath: /var/run/docker.sock
          readOnly: true
        - name: containerdsock
          mountPath: {{ .Values.containerdSockPath | default "/run/containerd/containerd.sock" }}
          readOnly: true
        - name: varlibdocker
          mountPath: /var/lib/docker
          readOnly: true
        env:
        - name: EVENTS
          value: "1"
        - name: PING
          value: "1"
        - name: VERSION
          value: "1"
        - name: AUTH
          value: "0"
        - name: SECRETS
          value: "0"
        - name: POST
          value: "0"
        - name: BUILD
          value: "0"
        - name: COMMIT
          value: "0"
        - name: CONFIG
          value: "0"
        - name: CONTAINERS
          value: "1"
        - name: DISTRIBUTION
          value: "0"
        - name: EXEC
          value: "0"
        - name: IMAGES
          value: "0"
        - name: INFO
          value: "0"
        - name: NETWORKS
          value: "0"
        - name: NODES
          value: "0"
        - name: PLUGINS
          value: "0"
        - name: SERVICES
          value: "0"
        - name: SESSION
          value: "0"
        - name: SWARM
          value: "0"
        - name: SYSTEM
          value: "0"
        - name: TASKS
          value: "0"
        - name: VOLUMES
          value: "0"
      volumes:
      - name: cwagentconfig
        configMap:
          name: {{ include "cloudzero-cloudwatch-metrics.fullname" . }}
      - name: rootfs
        hostPath:
          path: /
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: varlibdocker
        hostPath:
          path: /var/lib/docker
      - name: containerdsock
        hostPath:
          path: {{ .Values.containerdSockPath | default "/run/containerd/containerd.sock" }}
      - name: sys
        hostPath:
          path: /sys
      - name: devdisk
        hostPath:
          path: /dev/disk/
      - name: haproxypid
        hostPath:
          path: /run/haproxy.pid
      terminationGracePeriodSeconds: 60
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
