name: Main Push Continuous Deployment
on:
  push:
    branches:
      - main
jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: installing tool chain
        run: ./scripts/install-toolchain.sh

      - name: get fetch to update tags locally
        run: git fetch --prune --unshallow --tags

      - name: verify the release one more time.
        run: make all

      - name: Draft release
        run: ./scripts/draft-release.sh

      - name: Package release
        run: ./scripts/package-charts.sh

      - name: Publish Charts to repository (gh-pages)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTIONS: ${{ secrets.GITHUB_ACTIONS }}
        run: ./scripts/publish-charts.sh
          
      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          TAG_CONTEXT: repo

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ./build/release-notes.md
          files: ./build/stable/*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_RUN_NUMBER: release_V${{ env.GITHUB_RUN_NUMBER }}

